# This file is a template, and might need editing before it works on your project.
# This is a sample GitLab CI/CD configuration file that should run without any modifications.
# It demonstrates a basic 3 stage CI/CD pipeline. Instead of real tests or scripts,
# it uses echo commands to simulate the pipeline execution.
#
# A pipeline is composed of independent jobs that run scripts, grouped into stages.
# Stages run in sequential order, but jobs within stages run in parallel.
#
# For more information, see: https://docs.gitlab.com/ee/ci/yaml/README.html#stages

stages:          # List of stages for jobs, and their order of execution
  - build
  - test

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - echo "$CI_MERGE_REQUEST_TITLE"
    - echo "$CI_COMMIT_MESSAGE"
    - echo "Compile complete."
    - echo "This message shouldn't be seen, execpt for manual executions and in develop"
  only: 
    - develop
  except:
    - manual

test_job:
  stage: test
  script:
    - echo "Hi, this job always executes"
    - echo $CI_MERGE_REQUEST_TITLE
    - echo $CI_COMMIT_BRANCH

