stages: 
  - test

before_script:
  - python -V  # Print out python version for debugging
  - Rscript -e 'print(R.version())'

  
test_one:
  stage: test
  tags: 
  - test
  - sandbox
  script:
    - python hello_world.py

test_two:
  stage: test
  tags:
    - test
    - sandbox
  script: 
    - Rscript hello_world.R