image: python:3.9

before_script:
  - python -V  # Print out python version for debugging

prepare_env:
- pip install -r requirements.txt

test:
  tags:
    - test
  script:
    - pwd
    - python test_hello_world.py
